Fix NotImplementedError call in run_command method
The run_command method implemented in Runner raises an
NotImplementedError, because it should be overwritten by a function that
inherits from it (like Runner:Python).

Previously, the function called NotImplementedError, which is an
exception class, as a function:

    raise NotImplementedError("`Runner` subclasses must implement `run_command`")

This produced NoMethodErrors instead of NotImplementedErrors, as
NotImplementedError is an undefined method:

    NoMethodError:
        undefined method `NotImplementedError' for #<Runner::Python:0x00007f7c1323cd00>

This patch calls the raise method with NotImplementedError and the
message separately instead, which is what was meant, to produce proper
NotImplementedErrors:

    NotImplementedError:
        `Runner` subclasses must implement `run_command`