Use webrick for mock web server
For some reason thin doesn't accept any connections locally for me. I
get the following error from the Elixir integration:

``
  Error: Something went wrong while submitting the report to AppSignal.
econnrefused
```

I swapped back to webrick, which is what we used by default on Ruby < 3
previously.