Fix diagnose output matcher
I got this error when performing this spec. Match a String instead
so the error goes away.

> RegexpError: empty char-class